---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    boxes:
      - rockylinux8
      - centos7
      - debian11
      - debian10
      - debian9
      - ubuntu1804
      - ubuntu2004
      - ubuntu2204
    versions: {}

  tasks:

    - include_tasks: shared/build-a-box.yml
      with_items: "{{ boxes }}"
