---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - { role: geerlingguy.packer-debian, vmware_install_open_vm_tools: '{{vmware_install_open_vm_tools}}' }

  tasks:

    - name: Install 
      apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim

